### ISSUE TITLE
Usability & documentation updates for v1.0.0 release

### ISSUE THREAD

**Issue by AndrewFasano** [rehosting/penguin#128]
For our v1.0.0 release, we'll want to have some polished interfaces with updated documentation that can get a new user up to speed.

- [x] Polish interface: #148 / #149
- [x] Update `fw2tar` with similar polished CLI interface
- [x] Describe configuration options: #160 
- [x] Add a mechanism for viewing documentation if a user only has the container #162
- [X] Make `penguin init` have less gross `WARNING` messages about long paths being excluded from init choices and add a message about `/host` paths like we have for `penguin run`.

**Log messages / output**
- [x] On `run` command, penguin should report the output directory that results will be logged at. #180
- [x] On `init` command, penguin should print the message about `/host` paths if any are present, like what it does for `run`. #180
- [x] At the end of each run we log 2 messages about coverage and indicate that no coverage data is written - what's going here and this supposed to happen - #183
- [x] Update root shell prompt to indicate that it's a penguin shell and show project name #197  

**Documentation**
- [x] Support markdown viewing in terminal with `docs` sub-action #182
- [x]  Refactor docs into `./docs` directory (keeping a top level README in place for github viewing)
- [x] Add a step-by-step walkthrough for rehosting a simple target (ideally one where manual interventions are necessary) #201
    - [x] Blocked by #199
- [x] Run through documentation to identify where commands and paths are incorrect #202

Related (but not something we're aiming for with the v1.0.0 release): #140
